# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Task0905-VIPER' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Task0905-VIPER
  pod 'AlamofireImage', '~> 3.3'

end
